version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend