version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    image: veerabrahmam000/my-backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase

  frontend:
    image: veerabrahmam000/my-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend